### PR TITLE
fix #2

### LINKED ISSUE #2: Build broken
Build fails with `error: 'NetworkConnection' was not declared in this scope` due to [this](https://github.com/andersc/cppSRTWrapper/commit/b8ab0c5eea41d5627a86fb4b11ee9e812cb8e39f) change in cppSRTWrapper dependency

### PR DESCRIPTION
**Pull request by ghostnumber7**
Change NetworkConnection to SRTNet namespace

### CODE REVIEW

**Comment by andersc** [comment]
There is some changes to the MacOS environment variables in Github actions. That's why the MacOS build fails.. Will fix.

**Comment by ghostnumber7** [comment]
> There is some changes to the MacOS environment variables in Github actions. That's why the MacOS build fails.. Will fix.

yep. I'll send a PR in a while with that fix. I already have the one for MacOS, and trying to fix the CentOS one

**Comment by andersc** [comment]
The CentOS failure is due to that I did shut that build server down. I will restore that during the weekend. So you do not 'probably' need to fix anything.

**Comment by ghostnumber7** [comment]
> The CentOS failure is due to that I did shut that build server down. I will restore that during the weekend. So you do not 'probably' need to fix anything.

Oh ... I was trying to make it work with docker inside ubuntu. Takes forever (~15 min) but would work. If you prefer I'll ignore it then and send PR for Mac only

**Pull request merged**
